#pragma once

#include <SDL2/SDL.h>
#include <cstdio>
#include <pu/Plutonium>
#include <string>
#include <vector>

namespace pksm::utils {

// The PKSS v2 box-art sheet: verbatim JPEG blobs behind a sorted u64
// title-id index, generated by the out-of-repo pkss tool (format spec
// lives with it). One index serves both save universes: synthetic
// emulator-catalog ids and real Switch console title ids. Unlike the
// Pokémon SpriteSheet this has no hot path - catalog tiles decode once
// per refresh - so the file stays on disk and each lookup reads only
// its own blob.
class BoxArtSheet {
public:
    BoxArtSheet() = default;
    // Owns a raw FILE*; a copy would double-close it
    BoxArtSheet(const BoxArtSheet&) = delete;
    BoxArtSheet& operator=(const BoxArtSheet&) = delete;
    ~BoxArtSheet();

    bool Load(const std::string& path);

    // Decode the entry's JPEG into a fresh texture the caller owns;
    // nullptr when the id has no entry or decoding fails
    SDL_Texture* CreateTexture(u64 titleId);

private:
    struct IndexEntry {
        u64 key;
        u32 dataOffset;
        u32 dataSize;
    };
    static_assert(sizeof(IndexEntry) == 16);

    std::vector<IndexEntry> index;
    FILE* file = nullptr;
};

}  // namespace pksm::utils
