/*  This file is part of PKSM
>	Copyright (C) 2016/2017 Bernardo Giordano
>
>   This program is free software: you can redistribute it and/or modify
>   it under the terms of the GNU General Public License as published by
>   the Free Software Foundation, either version 3 of the License, or
>   (at your option) any later version.
>
>   This program is distributed in the hope that it will be useful,
>   but WITHOUT ANY WARRANTY; without even the implied warranty of
>   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>   GNU General Public License for more details.
>
>   You should have received a copy of the GNU General Public License
>   along with this program.  If not, see <http://www.gnu.org/licenses/>.
>   See LICENSE for information.
*/

#include "fill.h"

int count = 0;

int fill_get_index() {
	return count;
}

void fill_arrays(char *database[], int spriteArray[]) {
	while (!(count % 10 == 0)) {
		database[count] = " ";
		spriteArray[count++] = -1;	
	}
}

void filldatabase7(char *database[], int spriteArray[]) {
	count = 0;
	
	// database[count] = "0000 - Mewnium Z"; spriteArray[count++] = 0;
	// database[count] = "0201 - Birthday Events"; spriteArray[count++] = 764;
	database[count] = "0202 - Revival Herb"; spriteArray[count++] = 0;
	// database[count] = "0203 - PC Alolan Vulpix"; spriteArray[count++] = 37;
	// database[count] = "0204 - Item Bundle"; spriteArray[count++] = 0;
	database[count] = "0205 - Choice Band/Scarf"; spriteArray[count++] = 0;
	// database[count] = "0207 - Big Nugget"; spriteArray[count++] = 0;
	database[count] = "0208 - Rare Candy"; spriteArray[count++] = 0;
	database[count] = "0210 - Gold Bottle Cap"; spriteArray[count++] = 0;
	// database[count] = "0211 - PC Icy items"; spriteArray[count++] = 0;	
	database[count] = "0218 - Lunar Shiny Magikarp"; spriteArray[count++] = 129;
	database[count] = "0219 - 7-11 Machamp"; spriteArray[count++] = 68;
	database[count] = "0220 - Shiny Tapu Koko"; spriteArray[count++] = 785;
	database[count] = "0221 - JPN Egg Shiny Chance"; spriteArray[count++] = 747;
	// database[count] = "0222 - JPN Bewear"; spriteArray[count++] = 760;
	database[count] = "0223 - Ash-hat Pikachu"; spriteArray[count++] = 25;
	database[count] = "0224 - CoroCoro Charizard"; spriteArray[count++] = 6;
	database[count] = "0225 - Battle Points"; spriteArray[count++] = 0;
	database[count] = "0227 - Bestow Pikachu"; spriteArray[count++] = 25;
	database[count] = "0228 - Prerelease Marshadow"; spriteArray[count++] = 802;
	database[count] = "0229 - Movie Ho-Oh"; spriteArray[count++] = 250;
	database[count] = "0230 - Colorful Friends"; spriteArray[count++] = 133;
	database[count] = "0231 - Tohoku Victini"; spriteArray[count++] = 494;
	database[count] = "0233 - HK Shiny Tapu Koko"; spriteArray[count++] = 785;
	database[count] = "0234 - Anime Steenee"; spriteArray[count++] = 762;
	database[count] = "0235 - Anime Turtonator"; spriteArray[count++] = 776;
	database[count] = "0236 - Anime Vulpix"; spriteArray[count++] = 37;
	database[count] = "0238 - 7-11 Mew"; spriteArray[count++] = 151;
	database[count] = "0244 - Anime Trio"; spriteArray[count++] = 762;
	database[count] = "0247 - 7-11 Mew"; spriteArray[count++] = 151;
	database[count] = "0599 - Bottle Cap"; spriteArray[count++] = 0;
	database[count] = "0606 - Rocky Lycanroc"; spriteArray[count++] = 745;
	database[count] = "0613 - EU Shiny Tapu Koko"; spriteArray[count++] = 785;
	database[count] = "0615 - Nats Arcanine"; spriteArray[count++] = 59;
	// database[count] = "1105 - Shiny Tapu Koko"; spriteArray[count++] = 785;
	database[count] = "1107 - Alolan Vulpix"; spriteArray[count++] = 37;
	database[count] = "1108 - Alolan Sandshrew"; spriteArray[count++] = 27;
	database[count] = "1109 - Alolan Diglett"; spriteArray[count++] = 50;
	database[count] = "1110 - Alolan Grimer"; spriteArray[count++] = 88;
	// database[count] = "1111 - KOR Egg Shiny Chance"; spriteArray[count++] = 780;
	// database[count] = "1112 - WCSK17 Mew"; spriteArray[count++] = 151;
	database[count] = "1114 - Birthday Events"; spriteArray[count++] = 133;
	database[count] = "1601 - Z-stone Munchlax"; spriteArray[count++] = 446;
	database[count] = "1602 - Quick Balls"; spriteArray[count++] = 0;
	database[count] = "1603 - Poke Balls"; spriteArray[count++] = 0;
	database[count] = "1604 - Rare Candy"; spriteArray[count++] = 0;
	database[count] = "1605 - Mewtwoite X/Y"; spriteArray[count++] = 0;
	database[count] = "1606 - Mawilite"; spriteArray[count++] = 0;
	database[count] = "1607 - Rare Candy"; spriteArray[count++] = 0;
	database[count] = "1608 - Pidgeot-Steelixite"; spriteArray[count++] = 0;
	database[count] = "1609 - Mawilite"; spriteArray[count++] = 0;
	database[count] = "1610 - Rare Candy"; spriteArray[count++] = 0;
	database[count] = "1611 - 4 Mega Stones"; spriteArray[count++] = 0;
	database[count] = "1612 - PGL Prize"; spriteArray[count++] = 0;
	database[count] = "1613 - PGL Prize"; spriteArray[count++] = 0;
	database[count] = "1614 - PGL Prize"; spriteArray[count++] = 0;
	database[count] = "1615 - PGL Prize"; spriteArray[count++] = 0;
	database[count] = "1616 - PGL Prize"; spriteArray[count++] = 0;
	database[count] = "1617 - PGL Prize"; spriteArray[count++] = 0;
	database[count] = "1618 - PGL Prize"; spriteArray[count++] = 0;
	database[count] = "1622 - PGL Prize"; spriteArray[count++] = 0;
	// database[count] = "2040 - Stardust"; spriteArray[count++] = 0;
	// database[count] = "2041 - Star Piece"; spriteArray[count++] = 0;
	// database[count] = "2042 - Nugget"; spriteArray[count++] = 0;
	// database[count] = "2043 - Pretty Wings"; spriteArray[count++] = 0;
	// database[count] = "2044 - Balm Mushroom"; spriteArray[count++] = 0;
	// database[count] = "2045 - Comet Shard"; spriteArray[count++] = 0;
	// database[count] = "2046 - Ash Greninja"; spriteArray[count++] = 658;
	database[count] = "2047 - PGL 50BP"; spriteArray[count++] = 0;
	
	fill_arrays(database, spriteArray);
}

void filldatabase6(char *database[], int spriteArray[]) {
	count = 0;

	database[count] = "0001 - Birthday events"; spriteArray[count++] = 133;
	database[count] = "0002 - CoroCoro Garchomp"; spriteArray[count++] = 445;
	database[count] = "0003 - PC Tokyo Bay Inkay"; spriteArray[count++] = 686;
	database[count] = "0004 - Nuketta Wobbuffet"; spriteArray[count++] = 202;
	database[count] = "0008 - Lucky Egg"; spriteArray[count++] = 0;
	//database[count] = "0011 - Alternate Event Garchomp"; spriteArray[count++] = 445;
	database[count] = "0012 - Eevee House Sylveon"; spriteArray[count++] = 700;
	database[count] = "0015 - CoroCoro Charizard"; spriteArray[count++] = 6;
	//database[count] = "0017 - Garchomp"; spriteArray[count++] = 445;
	database[count] = "0019 - PC Scizor"; spriteArray[count++] = 212;
	database[count] = "0020 - PC Gengar"; spriteArray[count++] = 94;
	database[count] = "0021 - Darkrai"; spriteArray[count++] = 491;
	database[count] = "0022 - Diancie"; spriteArray[count++] = 719;
	database[count] = "0025 - M-Gyarados"; spriteArray[count++] = 130;
	database[count] = "0026 - M-Scizor"; spriteArray[count++] = 212;
	database[count] = "0027 - M-Kangaskhan"; spriteArray[count++] = 115;
	database[count] = "0028 - M-Gengar"; spriteArray[count++] = 94;
	database[count] = "0029 - M-Tyranitar"; spriteArray[count++] = 248;
	database[count] = "0030 - M-Mawile"; spriteArray[count++] = 303;
	database[count] = "0033 - Mega Kick Pikachu"; spriteArray[count++] = 25;
	database[count] = "0034 - Shiny Jirachi"; spriteArray[count++] = 385;
	database[count] = "0037 - Surf Incense Pikachu"; spriteArray[count++] = 25;
	database[count] = "0038 - Surf Balloon Pikachu"; spriteArray[count++] = 25;
	database[count] = "0039 - Surf, Shard Pikachu"; spriteArray[count++] = 25;
	database[count] = "0040 - Surf Focus Band Pikachu"; spriteArray[count++] = 25;
	database[count] = "0041 - Surf Silk Scarf Pikachu"; spriteArray[count++] = 25;
	database[count] = "0042 - Heart Stamp Pikachu"; spriteArray[count++] = 25;
	database[count] = "0043 - Charizard X/Y"; spriteArray[count++] = 6;
	database[count] = "0044 - Shiny Gengar"; spriteArray[count++] = 94;
	database[count] = "0045 - Tretta Rotom"; spriteArray[count++] = 479;
	database[count] = "0046 - Darkrai"; spriteArray[count++] = 491;
	database[count] = "0047 - Diancie"; spriteArray[count++] = 719;
	database[count] = "0048 - Birthday Events"; spriteArray[count++] = 133;
	database[count] = "0049 - Shiny Gengar"; spriteArray[count++] = 94;
	database[count] = "0050 - Pokescrap Shaymin"; spriteArray[count++] = 492;
	database[count] = "0051 - Pokescrap Keldeo"; spriteArray[count++] = 647;
	database[count] = "0052 - Pokescrap Victini"; spriteArray[count++] = 494;
	database[count] = "0053 - Nugget"; spriteArray[count++] = 0;
	database[count] = "0054 - Super Potions"; spriteArray[count++] = 0;
	database[count] = "0055 - Luxury Ball"; spriteArray[count++] = 0;
	database[count] = "0056 - Rare Candy"; spriteArray[count++] = 0;
	database[count] = "0057 - Master Ball"; spriteArray[count++] = 0;
	database[count] = "0058 - 12 Quick Balls"; spriteArray[count++] = 0;
	database[count] = "0059 - 100 Potions"; spriteArray[count++] = 0;
	database[count] = "0060 - 2 Master Balls"; spriteArray[count++] = 0;
	database[count] = "0061 - Shiny Jirachi"; spriteArray[count++] = 385;
	database[count] = "0062 - SSB4 Greninja"; spriteArray[count++] = 658;
	database[count] = "0063 - PC Piplup"; spriteArray[count++] = 393;
	database[count] = "0064 - PC Froakie"; spriteArray[count++] = 656;
	database[count] = "0065 - Shiny Charizard"; spriteArray[count++] = 6;
	database[count] = "0066 - Shiny Pikachu"; spriteArray[count++] = 25;
	database[count] = "0067 - Extremespeed Linoone"; spriteArray[count++] = 264;
	database[count] = "0071 - PC Eggs"; spriteArray[count++] = 322;
	database[count] = "0078 - Shiny Rayquaza"; spriteArray[count++] = 384;
	database[count] = "0079 - P-Cafe Pikachu"; spriteArray[count++] = 25;
	database[count] = "0081 - Movie Arceus"; spriteArray[count++] = 493;
	database[count] = "0082 - Movie Legends HA"; spriteArray[count++] = 383;
	database[count] = "0083 - Movie Hoopa"; spriteArray[count++] = 720;
	database[count] = "0086 - Serena's Fennekin"; spriteArray[count++] = 653;
	database[count] = "0088 - CoroCoro Rayquaza"; spriteArray[count++] = 384;
	database[count] = "0089 - Spring15 Kangaskhan"; spriteArray[count++] = 115;
	database[count] = "0090 - SG Shiny Rayquaza"; spriteArray[count++] = 384;
	database[count] = "0094 - PC Shiny Gyarados"; spriteArray[count++] = 130;
	database[count] = "0095 - Hiroshima PC Magikarp"; spriteArray[count++] = 129;
	database[count] = "0096 - Pokelab Bulbasaur"; spriteArray[count++] = 1;
	database[count] = "0097 - Pokelab Charmander"; spriteArray[count++] = 4;
	database[count] = "0098 - Pokelab Squirtle"; spriteArray[count++] = 7;
	database[count] = "0099 - 7/11 Pikachu"; spriteArray[count++] = 25;
	database[count] = "0100 - 7/11 Pancham"; spriteArray[count++] = 674;
	database[count] = "0101 - 7/11 Lugia"; spriteArray[count++] = 249;
	database[count] = "0102 - 7/11 Latios"; spriteArray[count++] = 381;
	database[count] = "0107 - Y.ama Shiny Pikachu"; spriteArray[count++] = 25;
	database[count] = "0108 - Tanabata 15 Jirachi"; spriteArray[count++] = 385;
	database[count] = "0109 - Satay King Pikachu"; spriteArray[count++] = 25;
	database[count] = "0110 - Manesh Hoopa"; spriteArray[count++] = 720;
	database[count] = "0111 - Shiny Xerneas, Yveltal"; spriteArray[count++] = 716;
	database[count] = "0113 - Zygarde"; spriteArray[count++] = 718;
	database[count] = "0114 - Expo Charizard"; spriteArray[count++] = 6;
	database[count] = "0115 - Expo Machamp"; spriteArray[count++] = 68;
	database[count] = "0116 - Expo Smeargle"; spriteArray[count++] = 235;
	database[count] = "0117 - Expo Zoroark"; spriteArray[count++] = 571;
	database[count] = "0119 - Nintendo HK Rayquaza"; spriteArray[count++] = 384;
	database[count] = "0120 - Universe Diancie"; spriteArray[count++] = 719;
	database[count] = "0121 - Birthday events"; spriteArray[count++] = 133;
	database[count] = "0122 - Halloween 2015 Pumpkaboo"; spriteArray[count++] = 710;
	database[count] = "0127 - Pokelab Chikorita"; spriteArray[count++] = 152;
	database[count] = "0128 - Pokelab Cyndaquil"; spriteArray[count++] = 155;
	database[count] = "0129 - Pokelab Totodile"; spriteArray[count++] = 158;
	database[count] = "0130 - WCS2015 Tyranitar"; spriteArray[count++] = 248;
	database[count] = "0131 - PC Shiny Diancie"; spriteArray[count++] = 719;
	database[count] = "0132 - PC Al/Au/Sa/Lu/Sl"; spriteArray[count++] = 334;
	database[count] = "0133 - PC Al/Au/Sa/Lu/Sl"; spriteArray[count++] = 531;
	database[count] = "0134 - PC Al/Au/Sa/Lu/Sl"; spriteArray[count++] = 448;
	database[count] = "0135 - PC Al/Au/Sa/Lu/Sl"; spriteArray[count++] = 80;
	database[count] = "0136 - PC Al/Au/Sa/Lu/Sl"; spriteArray[count++] = 302;
	database[count] = "0137 - VC Mew"; spriteArray[count++] = 151;
	database[count] = "0138 - Happy Hour Pikachu"; spriteArray[count++] = 25;
	database[count] = "0141 - Halloween Gengar"; spriteArray[count++] = 94;
	database[count] = "0142 - PC Eggs"; spriteArray[count++] = 322;
	database[count] = "0145 - HK Shiny Jirachi"; spriteArray[count++] = 385;
	database[count] = "0146 - SG Arceus"; spriteArray[count++] = 493;
	database[count] = "0147 - Scrap Eevee"; spriteArray[count++] = 133;
	database[count] = "0148 - Scrap Articuno"; spriteArray[count++] = 144;
	database[count] = "0149 - Scrap Zapdos"; spriteArray[count++] = 145;
	database[count] = "0150 - Scrap Moltres"; spriteArray[count++] = 146;
	database[count] = "0151 - Scrap 5 Rare Candy"; spriteArray[count++] = 0;
	database[count] = "0152 - Scrap Masterball"; spriteArray[count++] = 0;
	database[count] = "0153 - Scrap Venusaur"; spriteArray[count++] = 3;
	database[count] = "0154 - Scrap Charizard"; spriteArray[count++] = 6;
	database[count] = "0155 - Scrap Blastoise"; spriteArray[count++] = 9;
	database[count] = "0156 - Scrap Mewtwo"; spriteArray[count++] = 150;
	database[count] = "0157 - Max Revive"; spriteArray[count++] = 0;
	database[count] = "0158 - Masterball"; spriteArray[count++] = 0;
	database[count] = "0159 - Jade Infernape"; spriteArray[count++] = 392;
	database[count] = "0161 - Movie Volcanion"; spriteArray[count++] = 721;
	database[count] = "0162 - 720 Poll Greninja"; spriteArray[count++] = 658;
	database[count] = "0163 - Surf and Fly Pikachu"; spriteArray[count++] = 25;
	database[count] = "0164 - PC Shiny Ho-Oh"; spriteArray[count++] = 250;
	database[count] = "0165 - Masuda's Psyduck"; spriteArray[count++] = 54;
	database[count] = "0166 - Bestow Pikachu"; spriteArray[count++] = 25;
	database[count] = "0167 - Hyadain Landorus"; spriteArray[count++] = 645;
	database[count] = "0168 - Chymia's Gardevoir"; spriteArray[count++] = 282;
	database[count] = "0169 - Jarvis's Gengar"; spriteArray[count++] = 94;
	database[count] = "0170 - P-Cafe Pikachu (SG)"; spriteArray[count++] = 25;
	database[count] = "0171 - Skytree Rayquaza"; spriteArray[count++] = 384;
	database[count] = "0173 - HKTW VGC16 Shiny Mewtwo"; spriteArray[count++] = 150;
	database[count] = "0174 - Tanabata 2016 Jirachi"; spriteArray[count++] = 385;
	database[count] = "0175 - HKTW Mew"; spriteArray[count++] = 151;
	database[count] = "0176 - Poll Simisear"; spriteArray[count++] = 514;
	database[count] = "0177 - Giovanni's Nidoqueen"; spriteArray[count++] = 31;
	database[count] = "0178 - Maxie's Camerupt"; spriteArray[count++] = 323;
	database[count] = "0179 - Archie's Sharpedo"; spriteArray[count++] = 319;
	database[count] = "0180 - Cyrus' Weavile"; spriteArray[count++] = 461;
	database[count] = "0181 - Ghetsis' Hydreigon"; spriteArray[count++] = 635;
	database[count] = "0182 - Lysandre's Pyroar"; spriteArray[count++] = 668;
	database[count] = "0183 - Singa Volcanion"; spriteArray[count++] = 721;
	database[count] = "0184 - PC Bday 2016"; spriteArray[count++] = 133;
	database[count] = "0501 - Winter2013 Garchomp"; spriteArray[count++] = 445;
	database[count] = "0502 - Winter2013 Scizor"; spriteArray[count++] = 212;
	database[count] = "0504 - Magmar, Electabuzz"; spriteArray[count++] = 125;
	database[count] = "0510 - Arash's Mamoswine"; spriteArray[count++] = 473;
	database[count] = "0511 - Paris Vivillon"; spriteArray[count++] = 666;
	database[count] = "0512 - WORLD14 Aegislash"; spriteArray[count++] = 681;
	database[count] = "0514 - Tretta Wobbuffet"; spriteArray[count++] = 202;
	database[count] = "0515 - Heracross - Pinsir"; spriteArray[count++] = 214;
	database[count] = "0516 - Charizard X/Y"; spriteArray[count++] = 6;
	database[count] = "0518 - Heracronite"; spriteArray[count++] = 0;
	database[count] = "0523 - Halloween Pumpkaboo"; spriteArray[count++] = 710;
	database[count] = "0524 - Halloween Gengar"; spriteArray[count++] = 94;
	database[count] = "0525 - November Diancie"; spriteArray[count++] = 719;
	database[count] = "0527 - 100 Potions"; spriteArray[count++] = 0;
	database[count] = "0535 - WC14 Pachirisu"; spriteArray[count++] = 417;
	database[count] = "0536 - Phantom Force Darkrai"; spriteArray[count++] = 491;
	database[count] = "0537 - Shiny Charizard"; spriteArray[count++] = 6;
	database[count] = "0538 - GS Dragonite"; spriteArray[count++] = 149;
	database[count] = "0539 - World15 Sharpedo"; spriteArray[count++] = 319;
	database[count] = "0546 - Hope Diancie"; spriteArray[count++] = 719;
	database[count] = "0547 - Galileo Rayquaza"; spriteArray[count++] = 384;
	database[count] = "0551 - Aromatisse/Sableye"; spriteArray[count++] = 683;
	database[count] = "0552 - Bouffalant/Malamar"; spriteArray[count++] = 626;
	database[count] = "0553 - Harry Hoopa"; spriteArray[count++] = 720;
	database[count] = "0557 - GF Mew"; spriteArray[count++] = 151;
	database[count] = "0558 - GF Celebi"; spriteArray[count++] = 251;
	database[count] = "0559 - GF Jirachi"; spriteArray[count++] = 385;
	database[count] = "0560 - GF Darkrai"; spriteArray[count++]	= 491;
	database[count] = "0561 - GF Manaphy"; spriteArray[count++] = 490;
	database[count] = "0562 - GF Shaymin"; spriteArray[count++] = 492;
	database[count] = "0563 - GF Arceus"; spriteArray[count++] = 493;
	database[count] = "0564 - GF Victini"; spriteArray[count++] = 494;
	database[count] = "0565 - GF Keldeo"; spriteArray[count++] = 647;
	database[count] = "0566 - GF Genesect"; spriteArray[count++] = 649;
	database[count] = "0567 - GF Meloetta"; spriteArray[count++] = 648;
	database[count] = "0569 - Aldora Articuno"; spriteArray[count++] = 144;
	database[count] = "0570 - Aldora Zapdos"; spriteArray[count++] = 145;
	database[count] = "0571 - Aldora Moltres"; spriteArray[count++] = 146;
	database[count] = "0574 - Happy Meowth"; spriteArray[count++] = 52;
	database[count] = "0576 - Descartes Xerneas"; spriteArray[count++] = 716;
	database[count] = "0577 - Descartes Yveltal"; spriteArray[count++] = 717;
	database[count] = "0578 - Descartes Zygarde"; spriteArray[count++] = 718;
	database[count] = "0580 - Screenpeekaz Machamp"; spriteArray[count++] = 68;
	database[count] = "0586 - Play! Mewtwo"; spriteArray[count++] = 150;
	database[count] = "0588 - Helen Volcanion"; spriteArray[count++] = 721;
	database[count] = "0590 - WCS 2016 Bulbasaur"; spriteArray[count++] = 1;
	database[count] = "0591 - WCS 2016 Charmander"; spriteArray[count++] = 4;
	database[count] = "0592 - WCS 2016 Squirtle"; spriteArray[count++] = 7;
	database[count] = "0598 - Alexander Hoopa"; spriteArray[count++] = 720;
	database[count] = "0812 - Christmas Stantler"; spriteArray[count++] = 234;
	database[count] = "1001 - Eevee House Sylveon"; spriteArray[count++] = 700;
	//database[count] = "1004 - Olleh TV Charizard X/Y"; spriteArray[count++] = 6;
	//database[count] = "1005 - Alt. Event Garchomp"; spriteArray[count++] = 445;
	database[count] = "1006 - WCS14K Heracross"; spriteArray[count++] = 214;
	database[count] = "1007 - WCS14K Manectric"; spriteArray[count++] = 310;
	database[count] = "1008 - WCS14K Tyranitar"; spriteArray[count++] = 248;
	//database[count] = "1012 - WCS14K Pinsir"; spriteArray[count++] = 127;
	//database[count] = "1013 - WCS14K Houndoom"; spriteArray[count++] = 229;
	//database[count] = "1014 - WCS14K Aggron"; spriteArray[count++] = 306;
	database[count] = "1015 - Wishing Star Jirachi"; spriteArray[count++] = 385;
	database[count] = "1016 - Shiny Gengar"; spriteArray[count++] = 94;
	database[count] = "1017 - Movie Darkrai"; spriteArray[count++] = 491;
	database[count] = "1018 - Movie Diancie"; spriteArray[count++] = 719;
	database[count] = "1019 - Se Jun Park Pachirisu"; spriteArray[count++] = 417;
	database[count] = "1022 - 100 Potions"; spriteArray[count++] = 0;
	database[count] = "1023 - Guidebook Keldeo"; spriteArray[count++] = 647;
	database[count] = "1024 - Guidebook Shaymin"; spriteArray[count++] = 492;
	database[count] = "1025 - Guidebook Mareep"; spriteArray[count++] = 179;
	database[count] = "1026 - Extremespeed Linoone"; spriteArray[count++] = 264;
	database[count] = "1027 - Shiny Charizard"; spriteArray[count++] = 6;
	database[count] = "1029 - Shiny Rayquaza"; spriteArray[count++] = 384;
	database[count] = "1041 - Water Tribe Manaphy"; spriteArray[count++] = 490;
	database[count] = "1042 - Mega Battle 2015 Charizard"; spriteArray[count++] = 6;
	database[count] = "1043 - Shiny Pikachu"; spriteArray[count++] = 25;
	database[count] = "1047 - Movie Kyogre"; spriteArray[count++] = 382;
	database[count] = "1048 - Movie Groudon"; spriteArray[count++] = 383;
	database[count] = "1049 - Movie Dialga"; spriteArray[count++] = 483;
	database[count] = "1050 - Movie Palkia"; spriteArray[count++] = 484;
	database[count] = "1051 - Movie Giratina"; spriteArray[count++] = 487;
	database[count] = "1052 - Movie Kyurem"; spriteArray[count++] = 646;
	database[count] = "1053 - Movie Arceus"; spriteArray[count++] = 493;
	database[count] = "1054 - Movie Hoopa"; spriteArray[count++] = 720;
	database[count] = "1055 - Shiny Gyarados"; spriteArray[count++] = 130;
	database[count] = "1057 - 50 Quick Balls"; spriteArray[count++] = 0;
	database[count] = "1058 - KOR GF Mew"; spriteArray[count++] = 151;
	database[count] = "1060 - XYZ Xerneas"; spriteArray[count++] = 716;
	database[count] = "1061 - XYZ Yveltal"; spriteArray[count++] = 717;
	database[count] = "1062 - KOR XYZ Zygarde"; spriteArray[count++] = 718;
	database[count] = "1064 - XYZ Zygarde"; spriteArray[count++] = 718;
	database[count] = "1065 - KOR HA Articuno"; spriteArray[count++] = 144;
	database[count] = "1066 - KOR HA Zapdos"; spriteArray[count++] = 145;
	database[count] = "1067 - KOR HA Moltres"; spriteArray[count++] = 146;
	database[count] = "1068 - WCS16K HA Mewtwo"; spriteArray[count++] = 150;
	database[count] = "1070 - KOR Naminori Pikachu"; spriteArray[count++] = 25;
	database[count] = "1071 - KOR All Stars Diancie"; spriteArray[count++] = 719;
	database[count] = "1072 - KOR Gardevoir"; spriteArray[count++] = 282;
	database[count] = "1073 - KOR Gengar"; spriteArray[count++] = 94;
	database[count] = "1074 - KOR Tyranitar"; spriteArray[count++] = 248;
	database[count] = "1075 - KOR Mawile"; spriteArray[count++] = 303;
	database[count] = "1076 - KOR Victini"; spriteArray[count++] = 494;
	database[count] = "1078 - KOR Volcanion"; spriteArray[count++] = 721;
	database[count] = "1501 - HA Torchic"; spriteArray[count++] = 255;
	database[count] = "1502 - Quickballs"; spriteArray[count++] = 0;
	database[count] = "1503 - Fancy Vivillon"; spriteArray[count++] = 666;
	database[count] = "1504 - Shiny Beldum"; spriteArray[count++] = 374;
	database[count] = "1505 - HA Serperior"; spriteArray[count++] = 497;
	database[count] = "1506 - HA Emboar"; spriteArray[count++] = 500;
	database[count] = "1507 - HA Samurott"; spriteArray[count++] = 503;
	database[count] = "1508 - PGL Tyrunt"; spriteArray[count++] = 696;
	database[count] = "1509 - PGL Amaura"; spriteArray[count++] = 698;
	database[count] = "1510 - PGL Pikachu"; spriteArray[count++] = 25;
	database[count] = "1511 - Rare Candy"; spriteArray[count++] = 0;
	database[count] = "1512 - PGL Delibird"; spriteArray[count++] = 225;
	database[count] = "1513 - PGL Dragonite"; spriteArray[count++] = 149;
	database[count] = "1514 - PGL Miltank"; spriteArray[count++] = 241;
	database[count] = "1515 - PGL Garchomp"; spriteArray[count++] = 445;
	database[count] = "1516 - PGL N's Darmanitan"; spriteArray[count++] = 555;
	database[count] = "2048 - Eon Ticket"; spriteArray[count++] = 0;
	
	fill_arrays(database, spriteArray);
}

void filldatabase5(char *database[], int spriteArray[]) {	
	count = 0;
	
	database[count] = "000 - Liberty Pass"; spriteArray[count++] = 0;
	database[count] = "001 - Helpful Cubchoo"; spriteArray[count++] = 613;
	database[count] = "002 - Summer Karrablast"; spriteArray[count++] = 588;
	database[count] = "003 - Summer Shelmet"; spriteArray[count++] = 617;
	database[count] = "004 - TFE Electabuzz"; spriteArray[count++] = 125;
	database[count] = "005 - TFE Haunter"; spriteArray[count++] = 93;
	database[count] = "006 - TFE Machoke"; spriteArray[count++] = 67;
	database[count] = "007 - TFE Magmar"; spriteArray[count++] = 126;
	database[count] = "008 - TFE Scyther"; spriteArray[count++] = 123;
	database[count] = "009 - TFE Slowpoke"; spriteArray[count++] = 79;
	database[count] = "010 - TFE Karrablast"; spriteArray[count++] = 588;
	database[count] = "011 - TFE Shelmet"; spriteArray[count++] = 616;
	database[count] = "025 - Milos Island Tornadus"; spriteArray[count++] = 641;
	database[count] = "026 - Kalita's Hydreigon"; spriteArray[count++] = 635;
	database[count] = "027 - Spring 2012 Zekrom"; spriteArray[count++] = 644;
	database[count] = "028 - Darkrai"; spriteArray[count++] = 491;
	database[count] = "029 - Mysterious Egg Pidove"; spriteArray[count++] = 519;
	database[count] = "030 - Snarl Zoroark"; spriteArray[count++] = 571;
	database[count] = "031 - Satoshi's Scraggy"; spriteArray[count++] = 559;
	database[count] = "032 - Movie 2011 Victini"; spriteArray[count++] = 494;
	database[count] = "033 - Movie 2011 Reshiram"; spriteArray[count++] = 643;
	database[count] = "034 - Searcher Axew"; spriteArray[count++] = 610;
	database[count] = "035 - Janta's Golurk"; spriteArray[count++] = 623;
	database[count] = "036 - ANA Flying Pikachu"; spriteArray[count++] = 25;
	database[count] = "037 - Worlds 2011 Scrafty"; spriteArray[count++] = 560;
	database[count] = "038 - ELT Pikachu"; spriteArray[count++] = 25;
	database[count] = "039 - AAA Pikachu"; spriteArray[count++] = 25;
	database[count] = "040 - Chisa Pikachu"; spriteArray[count++] = 25;
	database[count] = "041 - Amigo Pikachu"; spriteArray[count++] = 25;
	database[count] = "042 - SKE48 Pikachu"; spriteArray[count++] = 25;
	database[count] = "043 - Wasshoi Pikachu"; spriteArray[count++] = 25;
	database[count] = "045 - Churuno Pikachu"; spriteArray[count++] = 25;
	database[count] = "048 - Mighty Mewtwo"; spriteArray[count++] = 150;
	database[count] = "049 - Tohoku Snivy"; spriteArray[count++] = 495;
	database[count] = "050 - BDay Audino 2011"; spriteArray[count++] = 531;
	database[count] = "051 - Milos Island Thundurus"; spriteArray[count++] = 642;
	database[count] = "052 - Master Ball"; spriteArray[count++] = 0;
	database[count] = "053 - Gratitude Shaymin"; spriteArray[count++] = 492;
	database[count] = "054 - YOTD egg Bagon"; spriteArray[count++] = 371;
	database[count] = "055 - YOTD Deino"; spriteArray[count++] = 633;
	database[count] = "056 - YOTD Druddigon"; spriteArray[count++] = 621;
	database[count] = "057 - YOTD Swablu"; spriteArray[count++] = 333;
	database[count] = "058 - Game Rayquaza"; spriteArray[count++] = 384;
	database[count] = "059 - Nobunaga Rayquaza"; spriteArray[count++] = 384;
	database[count] = "061 - Nationals 2012 Larvitar"; spriteArray[count++] = 246;
	database[count] = "062 - Nagasaki Blaziken"; spriteArray[count++] = 257;
	database[count] = "063 - Nagasaki Walrein"; spriteArray[count++] = 365;
	database[count] = "064 - Nagasaki Gardevoir"; spriteArray[count++] = 282;
	database[count] = "065 - Fukuoka Groudon"; spriteArray[count++] = 383;
	database[count] = "066 - Fukuoka Kyogre"; spriteArray[count++] = 382;
	database[count] = "067 - Sakura Pikachu"; spriteArray[count++] = 25;
	database[count] = "068 - Master Ball"; spriteArray[count++] = 0;
	database[count] = "069 - Summer Keldeo"; spriteArray[count++] = 647;
	database[count] = "070 - Movie 2012 Meloetta"; spriteArray[count++] = 648;
	database[count] = "071 - Strongest Pikachu"; spriteArray[count++] = 25;
	database[count] = "073 - Sasebo Ludicolo"; spriteArray[count++] = 272;
	database[count] = "075 - Saga Sceptile"; spriteArray[count++] = 254;
	database[count] = "076 - Saga Milotic"; spriteArray[count++] = 350;
	database[count] = "078 - Kumamoto Swampert"; spriteArray[count++] = 260;
	database[count] = "089 - SP Miyazaki Metagross"; spriteArray[count++] = 376;
	database[count] = "092 - Kokura Salamence"; spriteArray[count++] = 373;
	database[count] = "093 - Searcher Piplup"; spriteArray[count++] = 393;
	database[count] = "094 - Nats 2012 Volcarona"; spriteArray[count++] = 637;
	database[count] = "095 - Kanto Starter eggs"; spriteArray[count++] = 1;
	database[count] = "096 - Carnival Pikachu"; spriteArray[count++] = 25;
	database[count] = "097 - Singing Piplup"; spriteArray[count++] = 393;
	database[count] = "098 - Camp Aerodactyl"; spriteArray[count++] = 142;
	database[count] = "099 - Plasma Genesect"; spriteArray[count++] = 649;
	database[count] = "100 - Worlds 2012 Fly Pikachu"; spriteArray[count++] = 25;
	database[count] = "101 - Tag Ninetails"; spriteArray[count++] = 38;
	database[count] = "102 - Tag Chandelure"; spriteArray[count++] = 609;
	database[count] = "103 - Tag Whimsicott"; spriteArray[count++] = 547;
	database[count] = "104 - Tag Lucario"; spriteArray[count++] = 448;
	database[count] = "105 - YOTD Horsea"; spriteArray[count++] = 116;
	database[count] = "106 - YOTD Trapinch"; spriteArray[count++] = 328;
	database[count] = "111 - Strongest Dragonite"; spriteArray[count++] = 149;
	database[count] = "112 - Strongest Garchomp"; spriteArray[count++] = 445;
	database[count] = "113 - Strongest Metagross"; spriteArray[count++] = 376;
	database[count] = "114 - Strongest Scizor"; spriteArray[count++] = 212;
	database[count] = "115 - Strongest Tyranitar"; spriteArray[count++] = 248;
	database[count] = "118 - Anniversary Groudon"; spriteArray[count++] = 383;
	database[count] = "119 - Anniversary Kyogre"; spriteArray[count++] = 382;
	database[count] = "120 - Team Rocket Meowth"; spriteArray[count++] = 52;
	database[count] = "121 - Kanto egg Bulbasaur"; spriteArray[count++] = 1;
	database[count] = "122 - Kanto egg Charmander"; spriteArray[count++] = 4;
	database[count] = "123 - Kanto egg Squirtle"; spriteArray[count++] = 7;
	database[count] = "124 - Fukuoka BDay Audino"; spriteArray[count++] = 531;
	database[count] = "125 - Tohoku Victini"; spriteArray[count++] = 494;
	database[count] = "126 - Masuda Deoxys"; spriteArray[count++] = 386;
	database[count] = "127 - P2 Lab Genesect"; spriteArray[count++] = 649;
	database[count] = "128 - Winter Keldeo"; spriteArray[count++] = 647;
	database[count] = "129 - Spring Meloetta"; spriteArray[count++] = 648;
	database[count] = "130 - Abram's Cloyster"; spriteArray[count++] = 91;
	database[count] = "131 - Toler's Ludicolo"; spriteArray[count++] = 272;
	database[count] = "132 - Ray's Metagross"; spriteArray[count++] = 376;
	database[count] = "133 - Plasma Deoxys"; spriteArray[count++] = 386;
	database[count] = "134 - Nagoya Magikarp"; spriteArray[count++] = 129;
	database[count] = "135 - Movie 2013 Mewtwo"; spriteArray[count++] = 150;
	database[count] = "136 - Movie 2013 Genesect"; spriteArray[count++] = 649;
	database[count] = "137 - Decolora Jirachi"; spriteArray[count++] = 385;
	database[count] = "138 - Singing Eevee"; spriteArray[count++] = 133;
	database[count] = "139 - PCS Empoleon"; spriteArray[count++] = 395;
	database[count] = "140 - PCTH Serperior"; spriteArray[count++] = 497;
	database[count] = "141 - PCT Pikachu"; spriteArray[count++] = 25;
	database[count] = "142 - PCY Torterra"; spriteArray[count++] = 389;
	database[count] = "143 - PCN Infernape"; spriteArray[count++] = 392;
	database[count] = "144 - PCO Emboar"; spriteArray[count++] = 500;
	database[count] = "145 - PCF Samurott"; spriteArray[count++] = 503;
	database[count] = "147 - Singing Eevee"; spriteArray[count++] = 133;
	database[count] = "148 - Summer Shiny Dialga"; spriteArray[count++] = 483;
	database[count] = "149 - Summer Shiny Palkia"; spriteArray[count++] = 484;
	database[count] = "150 - Summer Shiny Giratina"; spriteArray[count++] = 487;
	database[count] = "151 - Tanabata Jirachi"; spriteArray[count++] = 385;
	database[count] = "152 - Strongest Pikachu"; spriteArray[count++] = 25;
	database[count] = "153 - Character Fair Jirachi"; spriteArray[count++] = 385;
	database[count] = "154 - Chilseok Jirachi"; spriteArray[count++] = 385;
	database[count] = "155 - Worlds 2013 Smeargle"; spriteArray[count++] = 235;
	database[count] = "156 - Alder's Volcarona"; spriteArray[count++] = 637;
	database[count] = "157 - Cynthia's Spiritomb"; spriteArray[count++] = 442;
	database[count] = "158 - Dento's Pansage"; spriteArray[count++] = 511;
	database[count] = "159 - Iris's Axew"; spriteArray[count++] = 610;
	database[count] = "160 - Prof Okido's Rotom"; spriteArray[count++] = 479;
	database[count] = "161 - Satoshi's Pikachu"; spriteArray[count++] = 25;
	database[count] = "162 - Do Heun's Hitmontop"; spriteArray[count++] = 237;
	database[count] = "163 - Seung Heon's Cresselia"; spriteArray[count++] = 488;
	database[count] = "164 - Sejun's Liepard"; spriteArray[count++] = 510;
	database[count] = "165 - Chief's Sableye"; spriteArray[count++] = 302;
	database[count] = "166 - Yamamoto's Politoed"; spriteArray[count++] = 186;
	database[count] = "167 - Tamamoto's Kingdra"; spriteArray[count++] = 230;
	
	fill_arrays(database, spriteArray);
}

void filldatabase4(char *database[], int spriteArray[]) {	
	count = 0;
	
	database[count] = "001 - TRU Manaphy"; spriteArray[count++] = 490;
	database[count] = "002 - Festa Electabuzz"; spriteArray[count++] = 125;
	database[count] = "003 - Festa Magmar"; spriteArray[count++] = 126;
	database[count] = "004 - NWS Manaphy"; spriteArray[count++] = 490;
	database[count] = "005 - JBHF Manaphy"; spriteArray[count++] = 490;
	database[count] = "006 - E4ALL Manaphy"; spriteArray[count++] = 490;
	database[count] = "007 - Sunday Tropius"; spriteArray[count++] = 357;
	database[count] = "008 - GameStop Deoxys"; spriteArray[count++] = 386;
	database[count] = "009 - Movie Darkrai"; spriteArray[count++] = 491;
	database[count] = "010 - Sunday Whiscash"; spriteArray[count++] = 340;
	database[count] = "011 - Pal City Lucario"; spriteArray[count++] = 448;
	database[count] = "012 - TRU Dragonite"; spriteArray[count++] = 149;
	database[count] = "013 - Nzone Pikachu"; spriteArray[count++] = 25;
	database[count] = "014 - Tanabata Jirachi 2007"; spriteArray[count++] = 385;
	database[count] = "015 - Bday Charmander"; spriteArray[count++] = 4;
	database[count] = "016 - Movie Shaymin"; spriteArray[count++] = 492;
	database[count] = "017 - Secret Key"; spriteArray[count++] = 0;
	database[count] = "018 - Member Card"; spriteArray[count++] = 0;
	database[count] = "019 - Movie Arceus"; spriteArray[count++] = 0;
	database[count] = "020 - Oak's Letter"; spriteArray[count++] = 0;
	database[count] = "021 - Pikachu-Colored Pichu"; spriteArray[count++] = 172;
	database[count] = "022 - Almia Darkrai"; spriteArray[count++] = 491;
	database[count] = "023 - Kyle Riolu"; spriteArray[count++] = 447;
	database[count] = "024 - Night Sky Jirachi"; spriteArray[count++] = 385;
	database[count] = "025 - Concert Chatot"; spriteArray[count++] = 441;
	database[count] = "026 - Pal City Manaphy"; spriteArray[count++] = 490;
	database[count] = "027 - Pal City Mew"; spriteArray[count++] = 151;
	database[count] = "028 - Matchup Checker"; spriteArray[count++] = 0;
	database[count] = "029 - Sunday Octillery"; spriteArray[count++] = 224;
	database[count] = "030 - Strongest Electivire"; spriteArray[count++] = 466;
	database[count] = "031 - Strongest Magmortar"; spriteArray[count++] = 467;
	database[count] = "032 - Strongest Milotic"; spriteArray[count++] = 350;
	database[count] = "033 - Strongest Dragonite"; spriteArray[count++] = 149;
	database[count] = "034 - Strongest Salamence"; spriteArray[count++] = 373;
	database[count] = "035 - McDonald's Pikachu"; spriteArray[count++] = 25;
	database[count] = "036 - Bday Charmander"; spriteArray[count++] = 4;
	database[count] = "037 - Tanabata Jirachi 2008"; spriteArray[count++] = 385;
	database[count] = "038 - PC Yokohama Pikachu"; spriteArray[count++] = 25;
	database[count] = "039 - Bday Pikachu 2008"; spriteArray[count++] = 25;
	database[count] = "040 - Eevee Collection"; spriteArray[count++] = 133;
	database[count] = "041 - Onemuri Pikachu"; spriteArray[count++] = 25;
	database[count] = "043 - Osaka Meowth"; spriteArray[count++] = 52;
	database[count] = "045 - Lucario Doll"; spriteArray[count++] = 0;
	database[count] = "047 - Bday Charmander 2009"; spriteArray[count++] = 4;
	database[count] = "048 - Yellow Forest Course"; spriteArray[count++] = 0;
	database[count] = "049 - Bday Chimchar 2009"; spriteArray[count++] = 390;
	database[count] = "050 - Kyoto Pikachu"; spriteArray[count++] = 25;
	database[count] = "051 - Winner's Path Course"; spriteArray[count++] = 0;
	database[count] = "052 - VGC10 Eevee"; spriteArray[count++] = 133;
	database[count] = "053 - Anniversary Mew"; spriteArray[count++] = 151;
	database[count] = "054 - Enigma Stone"; spriteArray[count++] = 0;
	database[count] = "055 - Shopping Course"; spriteArray[count++] = 0;
	database[count] = "056 - Ario Pikachu"; spriteArray[count++] = 25;
	database[count] = "057 - Bday Pikachu"; spriteArray[count++] = 25;
	database[count] = "058 - Event Course"; spriteArray[count++] = 0;
	database[count] = "059 - Winter Raikou"; spriteArray[count++] = 243;
	database[count] = "060 - Winter Entei"; spriteArray[count++] = 244;
	database[count] = "061 - Winter Suicune"; spriteArray[count++] = 245;
	database[count] = "062 - GameStop Celebi"; spriteArray[count++] = 251;
	database[count] = "063 - Goon's Scizor"; spriteArray[count++] = 212;
	database[count] = "064 - Amity Field Course"; spriteArray[count++] = 0;
	database[count] = "065 - Ash's Pikachu"; spriteArray[count++] = 25;
	database[count] = "066 - NZ Manaphy"; spriteArray[count++] = 490;
	database[count] = "067 - Bday Charmander 2010"; spriteArray[count++] = 4;
	database[count] = "068 - Worlds 2010 Crobat"; spriteArray[count++] = 169;
	database[count] = "069 - 7-Eleven Pikachu"; spriteArray[count++] = 25;
	database[count] = "070 - Bday Chimchar 2010"; spriteArray[count++] = 390;
	database[count] = "071 - Amity Field Course"; spriteArray[count++] = 0;
	database[count] = "072 - Battle Series Arcanine"; spriteArray[count++] = 59;
	database[count] = "073 - Hanguk Rayquaza"; spriteArray[count++] = 384;
	database[count] = "074 - Shinsegae Munchlax"; spriteArray[count++] = 446;
	database[count] = "075 - Shinsegae Feebas"; spriteArray[count++] = 349;
	database[count] = "076 - Character Fair Shaymin"; spriteArray[count++] = 492;
	database[count] = "077 - Character Fair Pikachu"; spriteArray[count++] = 25;
	database[count] = "078 - Sightseeing Course"; spriteArray[count++] = 0;
	database[count] = "079 - Manaphy Egg"; spriteArray[count++] = 490;
	database[count] = "080 - TCGWC Pikachu"; spriteArray[count++] = 25;
	database[count] = "090 - Azure Flute (unofficial)"; spriteArray[count++] = 0;
	database[count] = "108 - Apicot Berry"; spriteArray[count++] = 0;
	database[count] = "150 - Poketopia Pikachu"; spriteArray[count++] = 25;
	database[count] = "151 - Poketopia Electivire"; spriteArray[count++] = 466;
	database[count] = "152 - Poketopia Magmortar"; spriteArray[count++] = 467;
	database[count] = "153 - Worlds 2008 Lucario"; spriteArray[count++] = 448;
	database[count] = "154 - VGC09 Milotic"; spriteArray[count++] = 350;
	database[count] = "180 - Movie Regigigas"; spriteArray[count++] = 486;
	database[count] = "181 - Worlds 2009 Weavile"; spriteArray[count++] = 461;
	database[count] = "182 - Oblivia Deoxys (Attack)"; spriteArray[count++] = 386;
	database[count] = "183 - Oblivia Heatran"; spriteArray[count++] = 485;
	database[count] = "184 - Oblivia Shaymin"; spriteArray[count++] = 492;
	database[count] = "185 - Oblivia Deoxys (Defense)"; spriteArray[count++] = 386;
	database[count] = "186 - Oblivia Deoxys (Normal)"; spriteArray[count++] = 386;
	database[count] = "187 - Oblivia Deoxys (Speed)"; spriteArray[count++] = 386;
	
	fill_arrays(database, spriteArray);
}
